// <auto-generated />
namespace E_MeetingMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OrdinaryUserRole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrdinaryUserRole));
        
        string IMigrationMetadata.Id
        {
            get { return "201906231545153_OrdinaryUserRole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
